# Generated by Django 5.2.7 on 2025-11-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_alter_birthday_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='birthday',
            name='Uneque person constraint',
        ),
        migrations.AddConstraint(
            model_name='birthday',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'birthday'), name='Uneque person constraint'),
        ),
    ]
