# Generated by Django 5.2.7 on 2025-11-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0003_remove_birthday_uneque_person_constraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='image',
            field=models.ImageField(blank=True, upload_to='birthday_images', verbose_name='Фото'),
        ),
    ]
